### ISSUE TITLE
Checking and updating Glossary/Requirements pages

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#297]
**Issue Description:**

Our Glossary and Requirements pages were prepared last term, in Spring 2022. It should be updated for this term, considering the meeting with our assistant Alper Ahmetoğlu. 

**Tasks to Do:**

- [x] Check the Glossary and Requirements of the OLP
- [x] Consider the points that we have discussed with our assistant Alper Ahmetoğlu. 
- [x] Update the necessary points in the glossary and requirements. 

*Task Deadline:* 25.10.2022 14.00

*Final Situation:* Done. We had written a very nice requirements page last year. 

*Reviewer:* @mstfatay 

*Review Deadline:* 25.10.2022 15.00

**Comment by egetaga** [comment]
Couldn't find anything but the requirement 1.2.1.6. Removed it now. Want @mstfatay's review on the issue. Then it can be closed. 
<img width="612" alt="Screen Shot 2022-10-24 at 20 43 13" src="https://user-images.githubusercontent.com/42147612/197591616-171594e5-f72c-4cd0-93d4-2ed1df672606.png">

**Comment by mstfatay** [comment]
LGTM!
