### ISSUE TITLE
Learning Django - Ege Onur Taga

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#320]
Issue Description:

As a backend team, we have decided to learn Django throughly for the project before diving into implementation details. Thus, by following the tutorial [there](https://www.djangoproject.com/start/), I aim to finish the first four parts of the tutorial by implementing the first two sections. 

**Tasks to Do:**

- [x] Finish the reading of first two sections
- [x] Finish the implementation of first two sections
- [ ] Finish the first four parts of the tutorial. 

*Task Deadline:* 20.10.2022 23.59

*Final Situation:*

*Reviewer:*  @kkadirkkalkan 

*Review Deadline:* 21.10.2022 23.59

**Comment by egetaga** [comment]
On 16.10.2022 and 17.10.2022, I have read the first two parts of the tutorial and partially implemented the project on my local, except the last parts of the tutorial, i.e. the database integration.

**Comment by egetaga** [comment]
In yesterday's meeting, @mstfatay helped me learn the database integration. After his help, I finished the implementation of the first two chapters in [there](https://www.djangoproject.com/start/).

**Comment by egetaga** [comment]
I did finished the tutorial throughly. Since I finished everything, I am closing the issue.
