### ISSUE TITLE
Deployment on AWS EC2

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#342]
**Issue Description:**
As the backend team, we have divided the task between ourselves. My task was to deploy the dockerized project onto AWS EC2.

**Tasks to Do:**

- [x] Dockerize the project
- [x] Create an EC2 instance 
- [x] Deploy the demo project into AWS EC2
- [x] Deploy the real project into EC2

*Task Deadline:* 24.10.2022

*Final Situation:* Waiting for the app to finish. 

*Reviewer:*  @mstfatay 

*Review Deadline:* 25.10.2022

**Comment by egetaga** [comment]
In our meetings with @mstfatay and @kkadirkkalkan we have managed to dockerize the project. Most of the config files were already written by @kkadirkkalkan. We have changed them a bit to make it work. So, the docker file can be found in this:
[dockerfiles.zip](https://github.com/bounswe/bounswe2022group1/files/9853934/dockerfiles.zip)

**Comment by egetaga** [comment]
I created an EC2 instance with public ip 3.89.218.253. Port 8000, 80 are open to HTTP and HTTPS requests. I am attaching all open ports here: 

<img width="1149" alt="Screen Shot 2022-10-24 at 20 36 05" src="https://user-images.githubusercontent.com/42147612/197590090-928ad501-fff4-42e0-84e8-b968a0279b19.png">

**Comment by egetaga** [comment]
Dockerized and deployed onto AWS ECE2. For a quick demo you may check: http://3.89.218.253:8000/polls/. This is a demo. When a real endpoints comes, then I deploy it as well similarly.

**Comment by egetaga** [comment]
I have deployed the real backend application on AWS EC2, which you may check from [there](3.89.218.253:8000/app/register/). There are 4 functionalities as of now:

3.89.218.253:8000/app/register/
3.89.218.253:8000/app/login/
3.89.218.253:8000/app/logout/
3.89.218.253:8000/app/change-password/

I am closing the issue now.
