### ISSUE TITLE
Using Django REST framework

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#343]
**Issue Description:**
In order to send requests and receive responses we need to use rest api.

**Tasks to Do:**

- [x] Learn how to use Django REST framework
- [x] Create Django application for Budemi project
- [x] Set up the Django REST Framework for this applicaiton

*Task Deadline:* 25.10.2022 13.00 

*Final Situation:*
I am working on the task
*Reviewer:*  @mstfatay 

*Review Deadline:* 25.10.2022 13.00

**Comment by kkadirkkalkan** [comment]
Backend branch can be seen [here](https://github.com/bounswe/bounswe2022group1/tree/backend-dev/backend)
