### ISSUE TITLE
Dockerization and deployment of project

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#345]
**Issue Description:**

We need to learn how we can dockerize and deploy our project. The best way to learn them would be doing them. Therefore, we should dockerize and deploy our very first Django project.

**Tasks to Do:**

- [x] group up to discuss
- [x] dockerize the Django project
- [x] deploy the Django project

*Task Deadline:* 
25.10.2022 17:00PM

*Final Situation:*
See comment of @egetaga

**Comment by egetaga** [comment]
I have published the recent progress made in this issue. In summary:

- made the Dockerization and Deployment. 
- waiting for the final form of the project to deploy.
