### ISSUE TITLE
Pushing initial Django proect

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#354]
**Issue Description:**

We created the Django project as the backend team. Now it is time to push it to our repository. I will create an appropriate gitignore for our folder (backend), create a new branch for my team and push the project to the new branch.

**Tasks to Do:**

- [x] Create gitignore file for backend folder
- [x] create new branch for backend dev
- [x] Push Django project

*Task Deadline:* 
25.10.2022 17:00

*Final Situation:*
- Used [this gitignore file](https://djangowaves.com/tips-tricks/gitignore-for-a-django-project/)
- Crated new branch: [backend-dev](https://github.com/bounswe/bounswe2022group1/tree/backend-dev)
- Pushed the project: [commit](https://github.com/bounswe/bounswe2022group1/commit/f8a3f99f9f9a3cf725a44b30d56c2a520f5a0a5d)

*Reviewer:*  
@egetaga, @kkadirkkalkan 

*Review Deadline:*
26.10.2022 17:00

**Comment by apoorvthedude** [comment]
Hey @mstfatay .
Can i solve this issue ?
