### ISSUE TITLE
Implementing unit tests for register, login and logout

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#369]
**Issue Description:**
We should fully test the working of our application. Thus, I will be writing unit tests for register, login and logout APIs in the backend. 

**Tasks to Do:**

- [x] Implement register unittest
- [x] Implement login unittest
- [x] Implement logout unittest

*Task Deadline:* 29.10.2022

*Final Situation:* Done

*Reviewer:*  @kkadirkkalkan 

*Review Deadline:* 29.10.2022

**Comment by egetaga** [comment]
I have added Django unit tests, which you can check from this [PR](https://github.com/bounswe/bounswe2022group1/pull/367). It seems to work fine very nicely and @kkadirkkalkan already merged my PR and also reviewed it. Thus, I am closing my issue.
