### ISSUE TITLE
Frontend : Homepage v1 (template)

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#382]
**Issue Description:**

@hseyyidkaplan  did the sign-up and sign-in part of the project. After learning about it, I decided to make the homepage myself. I already designed the logo. I started making the site. Before hours, I learned what a homepage is, how it is made, what its common features are. Then I started doing it slowly. While I was doing it, I took samples from homepages on the internet. I learned the header, body and footer structure.

<img width="1436" alt="Screen Shot 2022-10-30 at 13 35 47" src="https://user-images.githubusercontent.com/74508086/198874197-0823953d-6724-4705-ae13-56d821277ef5.png">

<img width="1301" alt="Screen Shot 2022-10-30 at 13 35 58" src="https://user-images.githubusercontent.com/74508086/198874209-b776ca4c-a597-457d-b9fd-a051f339ea5b.png">

<img width="1436" alt="Screen Shot 2022-10-30 at 13 36 16" src="https://user-images.githubusercontent.com/74508086/198874218-f80616cf-4e6f-4283-805d-afe7437482e5.png">

<img width="1438" alt="Screen Shot 2022-10-30 at 13 36 33" src="https://user-images.githubusercontent.com/74508086/198874231-2b6e8770-057b-4a83-aecc-e6fca06d9910.png">

<img width="1438" alt="Screen Shot 2022-10-30 at 13 36 42" src="https://user-images.githubusercontent.com/74508086/198874236-e9028c58-5f9b-47e3-acea-683211bb8101.png">

<img width="1440" alt="Screen Shot 2022-10-30 at 13 36 54" src="https://user-images.githubusercontent.com/74508086/198874244-b04cdcb8-8e36-46d2-a378-2b005e88ab0a.png">

**Tasks to Do:**

- [x] Research on what homepage is
- [x] Learn what should it have
- [x] Learn how to iplement it

*Reviewer:*  @hseyyidkaplan 

*Review Deadline:* 02.11.2022 15.00

*Related Links:*
[What is Homepage?](https://www.techopedia.com/definition/5172/home-page)
[What is footer and header?](https://www.google.com/search?q=what+is+header+footer+body&oq=what+is+header+footer+body&aqs=chrome..69i57j33i10i160l2j33i22i29i30l7.6767j0j9&sourceid=chrome&ie=UTF-8)
[What should a homepage have?](https://blog.hubspot.com/blog/tabid/6307/bid/31097/12-critical-elements-every-homepage-must-have-infographic.aspx)

**Comment by hseyyidkaplan** [comment]
Very explanatory and well implemented code structure! Thanks.
