### ISSUE TITLE
Group meeting with the Android Team.

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#386]
**Issue Description:**

We need to meet again in order to make sure that we are ready for the milestone1.  The meeting will take place today starting from 20:00.

**Tasks to Do:**

- [x] Making sure that everyone's page is working
- [x] Making sure that everyone's page is working in harmony with each other's page.
- [x] We will put the final result into the budemi_android_main branch.

*Task Deadline:*  01.11.2022

**Comment by omerozdemir1** [comment]
The meeting is done. Here is [what we have done](https://github.com/bounswe/bounswe2022group1/tree/master/deliverables/CMPE451_Customer_Presentation_Milestone_1/android).
