### ISSUE TITLE
Frontend: for the v0.2, needs

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#387]
**Issue Description:**

Now, we are on the state [v0.2](https://github.com/bounswe/bounswe2022group1/tree/frontend-v0.2), so have some tasks to do.

**Tasks to Do:**

- [ ] The webpage is able to have token now, it needs to be saved through the session.
- [ ] The articles are needed to be related with the subject.
- [ ] We need a profile page.
- [ ] We need backend  implementation of "forgot password" link.

*Task Deadline:*  1.11.2022 11:00

*Reviewer:*  @hseyyidkaplan  @egetaga  @kkadirkkalkan  

*Review Deadline:*  15:00

**Comment by egetaga** [comment]
The backend implementation of "forgot password" link is left to after milestone. We will progress with current functionalities now.
