### ISSUE TITLE
Reorganizing Code Structure According to Last Changes

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#392]
**Issue Description:**

I should reorganize my code structure according to this commit: [https://github.com/bounswe/bounswe2022group1/commit/6807840ab3ff3f2c449731a485d6a2f936e55687](url)

**Tasks to Do:**

- [x] add issue labels
- [x] add reviewer
- [x] add related links
- [x] add API calls to sync authorization

*Task Deadline:* 30.10.2022 21:30

*Final Situation:*

*Reviewer:* @kadirgokhann 

*Review Deadline:* 31.10.2022 23:59

**Comment by hseyyidkaplan** [comment]
I did my tasks. @kadirgokhann You can follow the changes via this branch: [https://github.com/bounswe/bounswe2022group1/tree/react-authentication-page](url) and could you review it please?

**Comment by hseyyidkaplan** [comment]
Task is completed and I am closing the issue.
