### ISSUE TITLE
Frontend: Form Validation

### ISSUE THREAD

**Issue by kamilkorkut** [bounswe/bounswe2022group1#396]
**Issue Description:**

Form validations need to be implemented to sing-in and sign-up pages.

**Tasks to Do:**

- [x] research and learn React
- [x] research and learn how to implement form validation
- [x] implement form validation to the sign-in page
- [x] implement form validation to the sign-up page

*Task Deadline:*
31.10.2022

*Final Situation:*
The result can be seen [here](https://github.com/bounswe/bounswe2022group1/tree/react-authentication-page)

**Comment by kamilkorkut** [comment]
The tasks are done.
