### ISSUE TITLE
Create outline for the Customer Milestone 1 report

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#401]
**Issue Description:**

Create an outline for the Customer milestone 1 report

**Tasks to Do:**

- [x] create page
- [x] create sections
- [x] provide links for the existing deliverables
- [x] create subsections for team members in the alphabetical order of their surnames
- [x] share on the wiki page
- [x] export as .md when everyone has contributed

*Task Deadline:*  01.11.2022 11.00

*Final Situation:*

*Reviewer:*  @kadirgokhann 

*Review Deadline:* 01.11.2022 11.30
