### ISSUE TITLE
Create API documenatation

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#403]
**Issue Description:**
I will write API documentation for Budemi API. After that, I will create a page for it in our wiki and link the page to sidebar.

**Tasks to Do:**

- [x] write API documentation
- [x] create wiki page
- [x] link to sidebar

*Task Deadline:* 
31.10.2020 20:00

*Final Situation:*
API doc can be reached through [this link](https://github.com/bounswe/bounswe2022group1/wiki/API-Documentation).
It is also added to the sidebar.

*Reviewer:*  
@egetaga @kkadirkkalkan 

*Review Deadline:*
01.11.2020 20:00

**Comment by kkadirkkalkan** [comment]
API documentation is created and seems nice. Sİnce there is nothing left with this issue I am closing it.
