### ISSUE TITLE
Initialization of Android Studio

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#406]
**Issue Description:**

Determining which tools to use while doing the project.

**Tasks to Do:**

- [ ] Which ide to use for android app
- [ ] Which programming languages to use for app.
- [ ] version determination
- [ ] creating the project and committing it to github

*Task Deadline:* 

14.10.2022 22.00

*Reviewer:*  Osman Fehmi Albayrak

*Review Deadline:* 31.10.2022 22.00

**Comment by harunerkurt** [comment]
We decided to use android studio and develop with kotlin.
- Downloaded and upgraded the Android Studio.
- Downloaded Pixel 3a API 29 Device.
- Enabled Virtualization for my computer to run emulator.
- Created a basic login app with kotlin.
- I created the android main branch and pushed the relevant code.
