### ISSUE TITLE
Learning Android Studio and Kotlin

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#409]
Issue Description:

As a android team, we have decided to learn Android Studio and Kotlin throughly for the project before diving into implementation details. Thus, by following the tutorial [there](https://www.udemy.com/course/android-kotlin-developer/), I aim to finish the first two parts of the tutorial by implementing the first two sections. 

**Tasks to Do:**

- [x] Finish the watching of first four sections
- [x] Finish the implementation of first four sections
- [x] Finish the first six parts of the tutorial. 

*Task Deadline:* 20.10.2022 23.59

*Reviewer:*  @acyishere 

*Review Deadline:* 21.10.2022 23.59

**Comment by harunerkurt** [comment]
On 13.10.2022 and 14.10.2022, I have watched the first two parts of the tutorial and partially implemented the project on my local, except the last parts of the tutorial, i.e.

**Comment by harunerkurt** [comment]
I did finished the tutorial throughly.
