### ISSUE TITLE
Ege Onur Taga - Individual Contribution Report

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#416]
**Issue Description:**

I am going to add my contributions and aims for this milestone to the individual section of  [customer milestone 1 report](https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-1)

**Tasks to Do:**

- [x] About me, Member
- [x] Responsibilities, what am I supposed to do
- [x] My main contributions
- [x] Pull Requests
- [x] Additional Information

*Task Deadline:* 
01.11.2022 23.00

*Final Situation:*

*Reviewer:*  not needed

*Review Deadline:* -

**Comment by egetaga** [comment]
I have edited the document accordingly, [there](https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-1). Closing the issue, since nothing left to do.
