### ISSUE TITLE
Group meeting with the Android Team.

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#445]
**Issue Description:**

We need to meet again in order to make sure that we are ready for the milestone1.  The meeting will take place 31.10.2022 starting from 20:00.

**Tasks to Do:**

- [x] Making sure that everyone's page is working
- [x] Making sure that everyone's page is working in harmony with each other's page.
- [x] I will put the final result into the android_release branch.
- [x] Pull request to master branch

*Task Deadline:*  01.11.2022
