### ISSUE TITLE
Android - Preparation of milestone 1

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#446]
**Issue Description:**

Preparation of milestone 1

**Tasks to Do:**

- [x] Software Requirements Specification
- [x] Software Design (UML)
- [x] Scenarios and Mockups
- [x] Project Plan
- [x] Individual Contribution Reports

*Task Deadline:* 
01.11.2022 10.00

*Reviewer:*  
@omerozdemir1 @gecemavisioa @acyishere 

*Review Deadline:* 
01.11.2022 11.00
