### ISSUE TITLE
Individual Contribution Report

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#453]
**Issue Description:**

I will add my contributions for milestone 1 to the individual section of  [customer milestone 1 report](https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-1)

**Tasks to Do:**

- [x] About me, Member
- [x] Responsibilities, what am I supposed to do
- [x] My main contributions
- [x] Pull Requests

*Task Deadline:* 
01.11.2022 10.00

*Final Situation:*
It is completed

*Reviewer:*  @mstfatay 

*Review Deadline:* - 
01.11.2022 12.00

**Comment by mstfatay** [comment]
LGTM!
