### ISSUE TITLE
Ece Sarkın - Individual contribution to group report (Customer Milestone 1)

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#485]
**Description:** I should provide a description of my responsibilities and list my contribution in tabular format in Customer Milestone 1 Group Report.

**Tasks:**

- [x] write down my responsibilities
- [x] summary of individual work
- [x] merge it into [collabrative Wiki page](https://github.com/bounswe/bounswe2022group1/wiki/CMPE451-Group-Review-(Milestone-1))

**Deadline:** 04.11.2022 5PM
**Final situation:** My contribution is available [here](https://github.com/bounswe/bounswe2022group1/wiki/CMPE451-Group-Review-(Milestone-1)/2d0b8b8f946c1c6b34cdf690e006e1f84952423e)
