### ISSUE TITLE
Frontend: Open AWS account

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#488]
**Issue Description:**

Since we couldn't keep up with Milestone 1, I decided to pay attention to this issue. First I opened an aws account for myself. Then I learned what I could do in it and created a few instances for myself.

<img width="1440" alt="Screen Shot 2022-11-04 at 16 09 40" src="https://user-images.githubusercontent.com/74508086/199980108-e14c777e-2793-41d7-a504-a038970724b4.png">

**Tasks to Do:**

- [x] create an aws account
- [x] create an instanse
- [x] learn how to play with those

*Reviewer:*  @ecesrkn  

*Review Deadline:* 11.11.2022 15.00

Related Links:
[AWS](https://aws.amazon.com/tr/codedeploy/)

Final Actions:

**Comment by ecesrkn** [comment]
As the frontend team it was a challenge for us and we needed to pay more attention. I should also get familiar with this technology because we will be needing it soon again!
