### ISSUE TITLE
Contribute to Evaluation of Deliverables part of Milestone 1 

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#497]
**Issue Description:** 

I will contribute to evaluation of deliverables part of Milestone 1.

**Tasks to Do:**

- [x] Evaluate project plan Backend
- [x] Evaluate frontend Backend
- [x] Evaluate Individual Contribution reports

*Task Deadline:*  4/11/2022 20:00

*Final situation:*

I am working on it 

*Reviewer:*  @mstfatay

**Comment by kkadirkkalkan** [comment]
Evaluation of deliverables part of Milestone 1 is done. It can be seen [here](https://github.com/bounswe/bounswe2022group1/wiki/CMPE451-Group-Review-(Milestone-1))
