### ISSUE TITLE
Group Review (Milestone 1) - Evaluation of Deliverables

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#499]
**Issue Description:** 

I will write the Frontend Software, Project Plan Frontend and Group Review subtitles of Evaluation of Deriverables title in Group Review (Milestone 1) report.

**Tasks to Do:**

- [x] Add Frontend Software
- [x] Add Project Plan Frontend
- [x] Update the Group Review (Milestone 1) report

*Task Deadline:*  4/11/2022 21:30

*Reviewer* @kamilkorkut 

*Final situation: done*

**Comment by hseyyidkaplan** [comment]
I have just done this task. Could you please review @egetaga and if ok, change the label to 'Status: Completed' and close the issue?

**Comment by kamilkorkut** [comment]
It seems okay. I am closing the issue.

**Comment by egetaga** [comment]
Well done! Seems to be really well written.
