### ISSUE TITLE
Frontend: AWS Instance - Docker

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#509]
**Issue Description:**

We thought it would be logical to do the deposition part in advance due to the problem we had with the previous milestone. For this reason, I bought an aws instant and installed docker on it.
And in this process, I had some knowledge about AWS and tinkered with it for a while.

**Tasks to Do:**

- [x] create an AWS instance
- [x] learn how EC2 works
- [x] install docker on it

*Task Deadline:* 21.11.2022 13.00

*Final Situation:*

<img width="1562" alt="Screen Shot 2022-11-15 at 14 40 05" src="https://user-images.githubusercontent.com/74508086/201910789-b5a188fb-ac9c-4f49-b109-4bcb3d3e6dfb.png">

https://ec2-3-83-90-183.compute-1.amazonaws.com/

*Reviewer:*  @hseyyidkaplan  

*Review Deadline:* 21.11.2022 15.00

Related Links:

https://gist.github.com/kadirgokhann/2db33f7c51df4686329b2f5213203327
https://jsramblings.com/dockerizing-a-react-app/
