### ISSUE TITLE
Backend - edit content api

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#533]
**Issue Description:**

We should implement an API for editing content. 
- Any part of the content can be edited. 
- Only the owner of that content can edit the content.

 Note: This can be implemented by writing a put method in ContentApiView class.

**Tasks to Do:**

- [x] write a put method in ContentApiView
- [x] Make sure only the owner can edit the content
- [x] Update serializers and models if needed

*Task Deadline:* 
30.11.2022 13:00

*Final Situation:*
I implemented it. see [this pr](https://github.com/bounswe/bounswe2022group1/pull/538)

*Reviewer:*  
@kkadirkkalkan 

*Review Deadline:*
02.12.2022 17:00
