### ISSUE TITLE
Backend - implement tests for new endpoints (content, content-list, enroll)

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#534]
**Issue Description:** 
I have written content, content-list, and enroll endpoints. Although I have tested them via user tests, I couldn't find to write unit tests for them. Therefore, those endpoints' unit tests should be written.

**Tasks to Do:**
- [x] write unit tests for content endpoint
- [x] write unit tests for content-list endpoint
- [x] write unit tests for enroll endpoint

*Task Deadline:*  29/11/2022 7PM

*Final situation:
I wrote the tests. See the following pr: https://github.com/bounswe/bounswe2022group1/pull/633

*Reviewer* 

*Reviewer Deadline* 
06/12/2022 1PM

**Comment by kkadirkkalkan** [comment]
Nice job!
