### ISSUE TITLE
Backend - Implement User Profile Page Api

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#535]
**Issue Description:** 
We should implement APIs for the user profile page. On the user profile page those pieces of information will be shown:
- username
- email
- profile photo
- learning spaces that the user is enrolled
- last contributions that the user did (optional)
- some notes that the user took (optional) (Note: notes functionality is not implemented yet so I don't think we could do this right now)

There should be endpoints for:
- Getting a user's information
- Editing a user's information

I suppose that we will need to update our User model and serializers. 

**Tasks to Do:**

- [ ] Update models for user
- [ ] Implement an endpoint for getting user page information
- [ ] Write unit tests for the previous endpoint
- [ ] Implement an endpoint for updating user information
- [ ] Write unit tests for the previous endpoint

*Task Deadline:*  29/11/2022 7PM

*Final situation:

*Reviewer* 

*Reviewer Deadline*

**Comment by kkadirkkalkan** [comment]
I implemented the profile page API. The issue of profile page API can be seen [here](https://github.com/bounswe/bounswe2022group1/issues/558)
