### ISSUE TITLE
Frontend: Report of Group Meeting 28.11.2022

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#559]
**Issue Description:**

As discussed, the work distribution for Milestone 2 is as follows:
That words cover every unit of work related to that topic.

**Tasks to Do:**

- [ ] Sign in page,sign up page, homepage, profile page and routing between pages -> Kadir Gökhan Sezer
- [ ] Learning space page and learning space edit page -> Kamil Korkut and Huseyin Seyyid Kaplan
- [ ] Content page and content edit page -> Ece Sarkın
