### ISSUE TITLE
Unit Tests for APIs

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#620]
**Issue Description:** 
Unit tests for implemented APIs should be written. I have implemented profile, forget password, enrolled learning spaces and leave learning space endpoints.

**Tasks to Do:**
- [x] write unit tests for profile endpoint
- [x] write unit tests for forget password endpoint
- [x] write unit tests for getting enrolled learning spaces of a user endpoint
- [x] write unit tests for leave learning space endpoint

*Task Deadline:*  05/12/2022 11.30PM

*Final situation:
I started to write unit tests

*Reviewer* 
@mstfatay 

*Reviewer Deadline* 05/12/2022 11.30PM

**Comment by kkadirkkalkan** [comment]
by enrolled learning spaces endpoint I meant the endpoint to get the enrolled learning spaces of a user endpoint, not the enroll endpoint. I am going to edit the issue. Sorry for the misunderstanding.

**Comment by kkadirkkalkan** [comment]
I have written all of the unit tests except the profile test. I had some trouble writing the profile unit test and I am going to write this test later

**Comment by kkadirkkalkan** [comment]
I implemented unit test for profile page. Unit test can be seen via this [pull request](https://github.com/bounswe/bounswe2022group1/pull/849)
