### ISSUE TITLE
Frontend: Deployment

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#638]
**Issue Description:**

The frontend of the project needs to be deployed and reachable from some text(budemii.space).

**Tasks to Do:**

- [x] dockerize the project
- [x] buy a domain
- [x] buy a instance from AWS 
- [x] configure the instance
- [x] deploy the dockerized project 

*Task Deadline:* 05.12.2022 13.00
