### ISSUE TITLE
Completing Missing Tasks After Milestone 2

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#681]
**Issue Description:**

I didn't complete some of my duties for Milestone 2. I am working on them to catch up with our project and be coherent with my group members' works.

**Tasks to Do & Duration:**

- [x] add issue labels
- [x] add reviewer
- [x] add related links
- [x] watch short nextjs tutorial - **30min**
- [x] move latest folder structure to development and frontend branches - **15min**
- [x] move latest changes in [learningspace-detailpage ](https://github.com/bounswe/bounswe2022group1/tree/learningspace-detailpage/frontend)branch to[ ls-detailpage](https://github.com/bounswe/bounswe2022group1/tree/ls-detailpage) branch - **15min**
- [x] install dependencies & run nextjs project - **15min**
- [x] change background theme of LS - **15min**
- [x] take contents' element of page as parameters and adding them to the suitable places in a LS detail page - **45min**
- [x] form contents (text, video, picture) fit to the description in related API - **45min**
- [x] link API (content-get) to the endpoints - **45min**
- [x] implement join button to handle some membership and leaving from LS cases - **60min**

*Task Deadline: 11/12/2022 15:00*

*Final Situation:*

***Final Note:** I should be careful when determining tenures. It took 5 hours to complete these tasks. Totally, it took 10 hours with meetings, opening issues and checking and merging PRs.*

*Reviewer: @egetaga @omerozdemir1 @ecesrkn @uskudarli*

**Comment by hseyyidkaplan** [comment]
`1. I added join button functionality with endpoints. If user hasn't been joined yet, adding content  section doesn't appear to him.
`

==================================================================================

<img width="863" alt="image" src="https://user-images.githubusercontent.com/32467338/209493594-84b9f292-6f12-4867-9911-f095eab52d7c.png">

==================================================================================

`2. I added circular waiting image while uploading the contents of the page.`

==================================================================================

<img width="90" alt="image" src="https://user-images.githubusercontent.com/32467338/209493708-f7045d67-99ba-48d1-91a1-e26642d9bfe6.png">

==================================================================================

```
3. If a user joined the space, there will 3 changes on page front: 
- Join button turns to leave button with a full functionality
- Add content dropdown menu appers to user
- User added to members of this space and showed on page
```

==================================================================================

![image](https://user-images.githubusercontent.com/32467338/209493821-8cab0c47-0cc4-4195-b772-19c358404182.png)
