### ISSUE TITLE
Meeting with Kamil to Shape Our Roadmap

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#682]
**Issue Description:**

We set a meeting to shape our roadmap for incompleted tasks and determining Milestone 3 project plan. 
We decided complete our previous tasks according to specified sequence in this [issue](https://github.com/bounswe/bounswe2022group1/issues/681).
Meeting tooks approximately 1,5 hour.

**Tasks to Do:**

- [x] add issue labels
- [x] open issue for distributed tasks
- [x] link related issue

*Task Deadline: 9/12/2022 11:30 pm* 

*Final Situation: Completed*

**Comment by hseyyidkaplan** [comment]
All tasks done!
