### ISSUE TITLE
Missing tasks of milestone 2

### ISSUE THREAD

**Issue by kamilkorkut** [bounswe/bounswe2022group1#683]
**Issue Description:**
Some of the features were not completed and I will complete them.

**Tasks to Do:**

- [x] watching videos about nextjs
- [x] merging what I have done into the frontend branch
- [x] designing the learning space page to show the information about current learning space
- [ ] forming the content's (discussion, meeting) structure to fit to the description in related API
- [x]  linking content-post API to the endpoints
- [x]  linking learning space info API to the endpoints
- [x] implementing add-content functionality

*Task Deadline:* 
11/12/2022 15:00

*Final Situation:*
Add content functionality is added.

*Reviewer:*  

*Review Deadline:*

**Comment by kamilkorkut** [comment]
I have implemented displaying learning space information. The design will be improved and the page looks like this for now:

<img width="1440" alt="Screen Shot 2022-12-10 at 13 06 58" src="https://user-images.githubusercontent.com/73702922/206849862-f2142667-a1b3-4dc8-bba3-e6a4d4b98764.png">

**Comment by kamilkorkut** [comment]
I transferred what I have done before the milestone 2, but there is a style problem. I will try to fix it.

<img width="1440" alt="Screen Shot 2022-12-10 at 14 26 05" src="https://user-images.githubusercontent.com/73702922/206852637-34f71d7d-692c-4c4c-94c6-d9492fba6107.png">

**Comment by kamilkorkut** [comment]
I have implemented add content functionality.

Select the type of the content:
<img width="1440" alt="Screen Shot 2022-12-11 at 20 10 34" src="https://user-images.githubusercontent.com/73702922/206920492-d8d0c040-8300-47ff-9452-a0410bb12435.png">

Fill the form and send it. (for text)
<img width="1440" alt="Screen Shot 2022-12-11 at 20 48 50" src="https://user-images.githubusercontent.com/73702922/206920500-c59827e2-445c-4d29-9658-f0ffe5ba825c.png">

The response of adding text content: (url is empty)
<img width="368" alt="Screen Shot 2022-12-11 at 20 59 52" src="https://user-images.githubusercontent.com/73702922/206920506-ad89904c-f530-4f2a-ae71-5662913dfea8.png">

Fill the form and send it. (for image)
<img width="1440" alt="Screen Shot 2022-12-11 at 21 03 49" src="https://user-images.githubusercontent.com/73702922/206920629-6b2ae67a-6907-4cae-b2c7-e1429ee2bbde.png">

The response of adding image content: (text is empty)
<img width="359" alt="Screen Shot 2022-12-11 at 21 00 17" src="https://user-images.githubusercontent.com/73702922/206920513-ace5d031-519e-4b74-81f6-34a5f9d1cc37.png">
