### ISSUE TITLE
Reviewing & Merging Pull Request

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#685]
**Issue Description:**

I will review and then, if it is suitable, merge the Kamil's latest [pull request](https://github.com/bounswe/bounswe2022group1/pull/684).

**Tasks to Do:**

- [x] add issue labels
- [x] add related links
- [x] review pull request
- [x] merge pull request if it is ok

*Task Deadline: 11/12/2022 02:00 am* 

*Final Situation: done*

**Comment by hseyyidkaplan** [comment]
Completed!
