### ISSUE TITLE
Frontend: Add content functionality

### ISSUE THREAD

**Issue by kamilkorkut** [bounswe/bounswe2022group1#687]
**Issue Description:**

Add content section of the learning space must be work as we want.

**Tasks to Do:**

- [x] add add content dropdown menu
- [x] route depend on the selected type
- [x] connect it to the related api

*Task Deadline:* 
11.12.2022 23:00

*Final Situation:*

*Reviewer:*  

*Review Deadline:*

**Comment by kamilkorkut** [comment]
All done. You can see screenshots [here](https://github.com/bounswe/bounswe2022group1/issues/683)
