### ISSUE TITLE
Reviewing & Merging Pull Request

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#688]
**Issue Description:**

I will review and then, if it is suitable, merge the Kamil's latest [pull request](https://github.com/bounswe/bounswe2022group1/pull/686).

**Tasks to Do:**

- [ ] add issue labels
- [ ] add related links
- [ ] review pull request
- [ ] merge pull request if it is ok

*Task Deadline: 12/12/2022 11:00 am* 

*Final Situation:*
