### ISSUE TITLE
Objectives for Android Team until Milestone3 

### ISSUE THREAD

**Issue by omerozdemir1** [bounswe/bounswe2022group1#689]
**Issue Description:**
Until the milestone3, our objectives as Android Team is as follows

**Tasks to Do:**

- [ ] Determining Primary and Secondary colors to align with front-end team in terms of design.
- [ ] There is no content or such thing. Everything is a resource. Change the names accordingly.
- [ ] Resources should be added via markdown.
- [ ] Discussion, members and notes should be split into different pages for better UI/UX experience.
- [ ] Show attributes of learning spaces (members, upvotes etc.) for better UI/UX experience.
- [ ] Give shortcut for favorite learning space.
- [ ] Annotation functionality should be implemented.
- [ ] All designs should be reviewed for better UI/UX experience.

*Task Deadline:* 
27.12.2022

*Final Situation:*
In progress.

*Reviewer:*  
@gecemavisioa 
@acyishere 

*Review Deadline:*
27.12.2022

**Comment by omerozdemir1** [comment]
_Determining Primary and Secondary colors to align with front-end team in terms of design._
![image](https://user-images.githubusercontent.com/62199007/207746016-b03fb252-23f6-4abc-aa2a-880f064c5b71.png)
Related issue: https://github.com/bounswe/bounswe2022group1/issues/690

**Comment by omerozdemir1** [comment]
_See the folllowing design improvement._
https://github.com/bounswe/bounswe2022group1/issues/692

**Comment by omerozdemir1** [comment]
Design improvement is done. See the [PR#693](https://github.com/bounswe/bounswe2022group1/pull/693)

**Comment by omerozdemir1** [comment]
`Show attributes of learning spaces (members, upvotes etc.) for better UI/UX experience.`
Done.
