### ISSUE TITLE
Implementation and Editing Action Bar

### ISSUE THREAD

**Issue by acyishere** [bounswe/bounswe2022group1#707]
**Issue Description:**

I am going to implement and add new functionalities to action bar above the app

**Tasks to Do:**

- [ ] Customize the Action Bar
- [ ] Add Search Box
- [ ] Add Profile Button on Top
- [ ] Adjust the redirects.

*Task Deadline:* 
19.12.2022
*Final Situation:*
In progress
*Reviewer:*  
@gecemavisioa 
@omerozdemir1 
*Review Deadline:*
19.12.2022
