### ISSUE TITLE
Learning Space Related Endpoints Need to Be Updated

### ISSUE THREAD

**Issue by gecemavisioa** [bounswe/bounswe2022group1#712]
**Issue Description:**
Since we are going to display more details about learning spaces in the learning spaces list, we need more information returning from the related endpoints. Also, the endpoint for creating a learning space should be updated accordingly.
A description, created at time stamp and the owner fields should be added in addition to fields seen below:
![image](https://user-images.githubusercontent.com/73769340/208166842-5d6c23bc-c9b9-4c08-bed9-88de59067cf2.png)

**Tasks to Do:**

- [ ] Updating GET /app/learning-space-list/
- [ ] Updating GET /app/learning-space-tag-search/ 
- [ ] Updating GET /app/learning-space-search/
- [ ] Updating POST /app/learning-space/

*Task Deadline:* 
20.12.2022

*Final Situation:*
In progress.

*Reviewer:*  
@egetaga 
@kkadirkkalkan 

*Review Deadline:*
20.12.2022

**Comment by kkadirkkalkan** [comment]
I added requested fields to the learning space and updated related endpoints. Changes can be seen with this [pull request](https://github.com/bounswe/bounswe2022group1/pull/741)

**Comment by gecemavisioa** [comment]
Thanks for the update!
