### ISSUE TITLE
Frontend - Creating New UI Theme

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#720]
**Issue Description:**
The UI of frontend looks a little bit cheap. Therefore, we decided to update it. I also selected a new color palette and logo. I will try to update the UI according to the new color palette. I will be writing a generic theme in React for good reusability. I will fix broken margins, padding, and slipped components too.

**Tasks to Do:**

- [x] write a generic React theme according to new color palette
- [x] fix broken components, margins, and paddings
- [x] change the logo

*Task Deadline:* 
17.12.2022 20:00

*Final Situation:*
I created a generic Material UI theme and started updating the UI of the login and register pages. I had to see the new theme on a page visually and login pages are the most straightforward pages of our website. Therefore, I started from those pages.
I changed the logo too.

Commits:
- https://github.com/bounswe/bounswe2022group1/commit/325649278a247212fdf99eebbed96a566f13aef1
- https://github.com/bounswe/bounswe2022group1/commit/c563fc2970c423e92c737239d1248b63a0118905

Screenshots:

*Reviewer:*  
@kadirgokhann 

*Review Deadline:*
25.12.2022 20:00
