### ISSUE TITLE
Learning Space Fields

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#742]
**Issue Description:**
New fields should be added to learning space model. Frontend and mobile teams are requested this enhancement. Related issues are [issue1](https://github.com/bounswe/bounswe2022group1/issues/712) and [issue2](https://github.com/bounswe/bounswe2022group1/issues/729)

**Tasks to Do:**

- [x] add image filed
- [x] add description filed
- [x] add owner filed
- [x] add date filed

*Task Deadline:* 
20.12.2022- 15.00

*Final Situation:*

I have implemented these new features and updated related endpoints. Pull request can be seen [here](https://github.com/bounswe/bounswe2022group1/pull/741)

*Reviewer:*  
@egetaga 

*Review Deadline:*
20.12.2022- 15.00

**Comment by kkadirkkalkan** [comment]
I updated learning space model as required, therefore I am closing this issue.
