### ISSUE TITLE
Frontend - Updating UI of Profile Pages and Side Bar

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#753]
**Issue Description:**
I will continue UI updates with profile pages and sidebar. Our sidebar has the old logo. The profile pages - especially reset password page - have broken margins. I will be fixing them.

**Tasks to Do:**

- [x] update the logo of the sidebar
- [x] fix the margins and paddings of profile pages
- [x] more visual updates

*Task Deadline:* 
25.12.2022 20:00

*Final Situation:*
I updated the logo and fixed the paddings/margins. Furthermore, I adjusted the design too. For example, the divider wasn't used well and there were some misused react components (like a Box component was used instead of a Paper).
 
For further details, check the related commit: https://github.com/bounswe/bounswe2022group1/commit/688354d177053d5f2aefc706f8fd48a813b6b645

*Reviewer:*  

*Review Deadline:*
28.12.2022 20:00
