### ISSUE TITLE
Frontend - Annotation Research

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#785]
**Issue Description:**
I am responsible for text and image annotations from frontend team. I will make a research on how to do web annotations. I will be looking for the following third-party libraries:
- Recogito (https://github.com/recogito/recogito-js)
- Annotorious (https://github.com/recogito/annotorious/tree/v2.7.9)

As far as I know, Recogito is for text annotations and Annotorious is for image annotations. I will read documentations of these libraries and try to implement basic text and image annotations. 

**Tasks to Do:**

- [x] read docs of Recogito
- [x] read docs of Annotorious
- [x] implement a basic text annotation
- [x] implement a basic image annotation

*Task Deadline:* 
26.12.2022 12:00

*Final Situation:*
I made my research. The most tricky part was importing those libraries because they are not React but js libraries. Because we use Next.js's server rendering, those libraries were imported on the server side. However, the libraries use some browser-specific objects (like window object). Therefore, the imports were not successful. I solved the issue by using Next.js's dynamic imports. 
After that I implemented text and image annotations using these libraries. The default UI of pop ups that those libraries supply wasn't relevant to our theme. Therefore, I updated their UI too.
Deafult UI:
![WhatsApp Image 2022-12-24 at 22 19 48](https://user-images.githubusercontent.com/46002371/209452463-c8809031-3793-4094-b5f5-004d525cc55b.jpeg)

After UI update:
![image](https://user-images.githubusercontent.com/46002371/209452483-b1045f71-0240-4532-97d7-e10fbb22e3f5.png)

Commits:
https://github.com/bounswe/bounswe2022group1/commit/114829da54b67d74ef3df3b9f408a9294d073ba0

*Reviewer:*  

*Review Deadline:*
28.12.2022 14:00

**Comment by omerozdemir1** [comment]
Wow! You are the best. Thanks for the annotation.
