### ISSUE TITLE
Reviewing and Merging Pull Request 

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#797]
**Issue Description:**

I will review and if suitable merge [this](https://github.com/bounswe/bounswe2022group1/pull/726) pull request from Kamil.

**Tasks to Do:**

- [x] add issue labels
- [x] add related links
- [x] review changes
- [x] run changes on my own local
- [x] comment to PR
- [x] approve PR in case of bugless running
- [x] merge branch unless there are conflicts

*Task Deadline: 26/12/2022 6:00 am* 

*Final Situation: completed & branch merged to `frontend`*

**Comment by hseyyidkaplan** [comment]
All tasks were completed, I am closing this issue.
