### ISSUE TITLE
Adding 'upvote' Feature for a Learning Space

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#798]
**Issue Description:**

I will add `upvote` feature for a learning space and create a pull request for this new feature if it will be completed.

**Tasks to Do:**

- [ ] add issue labels
- [ ] add reviewer
- [ ] add related links
- [ ] open a branch named `upvote`
- [ ] search for `upvote` feature
- [ ] implement `upvote` feature
- [ ] create a PR

*Task Deadline: 25/12/2022 11:59 pm* 

*Final Situation:*

*Reviewer: @kamilkorkut*
