### ISSUE TITLE
Fixing 'join' Button for a Learning Space

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#801]
**Issue Description:**

There is a problem with `join` button: unless you push the button at least twice, it doesn't work. I will fix `join` button for a learning space and create a pull request for this new feature if it will be completed.

**Tasks to Do:**

- [x] add issue labels
- [x] add reviewer
- [x] add related links
- [x] open a branch named `join-button`
- [x] search for bug
- [x] update `join` button functionality
- [x] create a PR

*Task Deadline: 25/12/2022 11:59 pm* 

*Final Situation: problem was resolved, button works correctly*

*Reviewer: @kadirgokhann*

**Comment by hseyyidkaplan** [comment]
PR which was opened for this issue is merged by @kadirgokhann, I am closing this issue.
