### ISSUE TITLE
Reviewing Issues

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#802]
**Issue Description:**

I will review issues that I am assigned to review them. List of mentioned issues are below:

**Tasks to Do:**

- [ ] add issue labels
- [ ] add related links
- [ ] add comments to issues
- [ ] add related labels
- [ ] close completed issues

*Task Deadline: 26/12/2022 11:59 pm* 

*Final Situation:*
