### ISSUE TITLE
Frontend: Resource page

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#813]
**Issue Description:** We needed improvements on the last milestone's content page.

**Tasks to Do:**

- [x] The page layout and appearance should be like the profile page's
- [x] The name should change to resource
- [x] Contributors should appear with their name, not user id.

*Task Deadline:*  21.12.2022

*Final Situation:* The task is complete, @kadirgokhann and I worked on the contributors' related functionality during a Zoom session on 21.12.2022. We need further improvements like annotation, edit, and upvote.

This [commit](https://github.com/bounswe/bounswe2022group1/commit/d5dee1c734d7999ee6af48f02df41f9b60ebe181) is about this issue.

*Reviewer* @kadirgokhann
