### ISSUE TITLE
Frontend: Resource, edit page

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#817]
**Issue Description:** Resource should be editable by its owner.

**Tasks to Do:**

- [x] select the fields that are allowed to be edited.
- [x] add control for who should be able to edit.
- [x] implement edit page

*Task Deadline:* 26.12.2022 20.00

*Final Situation:* The task is complete. Add Content page by Kamil has also helped me a lot during the creation of this component. 

<img width="804" alt="image" src="https://user-images.githubusercontent.com/43001709/209571477-bac9f89e-b367-483b-b1f7-b8a5eab6c3c4.png">

The fields of the resource being edited are pre-loaded into the input fields.

*Reviewer:*  @mstfatay 

*Review Deadline:* 26.12.2022 10.00pm
