### ISSUE TITLE
Add an .env File to Backend Django Project

### ISSUE THREAD

**Issue by kkadirkkalkan** [bounswe/bounswe2022group1#834]
**Issue Description:**
The Django project doesn't run with the same database parameters on localhost and AWS machine. Therefore two env files should be created and database parameters in budemi/settings.py and docker-compose.yml files should be connected to these env parameters.

**Tasks to Do:**

- [x] create env file database parameters to run the project on localhost
- [x] create env file database parameters to run the project on AWS Machine
- [x] connect database parameters in budemi/settings.py and docker-compose.yml files to these env parameters

*Task Deadline:* 
26.12.2022- 17.00

*Final Situation:*
I created two different env files named env_sample and prod_sample. To run the project on localhost a .env file should be created and parameters in env_sample should be used. To run it on AWS machine prod_sample parameters need to be used.

*Reviewer:*  
@egetaga 

*Review Deadline:*
26.12.2022- 17.00

**Comment by kkadirkkalkan** [comment]
I committed changes and sent a pull request #789 about this issue.

**Comment by egetaga** [comment]
I reviewed the changes. Nice work!
