### ISSUE TITLE
Backend - Implementing annotations API

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#839]
**Issue Description:**

As a backend team, we should implement annotation API that supports post, get, patch and delete methods. With post, we will store W3C annotations and with get, we will retrieve all annotations of a given resource. With delete, we will delete annotation of a given id. 

**Tasks to Do:**

- [x] Implement GET endpoint
- [x] Implement POST endpoint
- [x] Implement the PATCH endpoint
- [x] Implement delete endpoint

*Task Deadline:* 26.12.2022

*Final Situation:* Done

*Reviewer:*  @kkadirkkalkan 

*Review Deadline:*

**Comment by egetaga** [comment]
I implemented all of the functionalities and mentioned them in the PR https://github.com/bounswe/bounswe2022group1/pull/788.

**Comment by kkadirkkalkan** [comment]
It was a difficult task thank you for your efforts. I am closing this issue.
