### ISSUE TITLE
Backend - Creating a project and deploying it into AWS EC2 instance for the annotations

### ISSUE THREAD

**Issue by egetaga** [bounswe/bounswe2022group1#840]
**Issue Description:**

For W3C compatibility, the annotations should be in a different database. The most efficient way of doing that for me to create a second Django project and deploy all the required functionalities there. So, we should create a Django project, implement the required functionalities, dockerize,  and deploy it into AWS EC2 instance. 

**Tasks to Do:**

- [x] Create a new Django project for the backend support of annotations. 
- [x] Implement the required annotation functionalities
- [x] Dockerize it
- [x] Deploy it into AWS EC2 instance

*Task Deadline:* 26.12.2022

*Final Situation:* Done

*Reviewer:*  @kkadirkkalkan

**Comment by egetaga** [comment]
I carried out all these tasks. Our annotations work on a different server on the AWS EC2 instance as I stated in my issue https://github.com/bounswe/bounswe2022group1/issues/839 

I implemented all of the functionalities and mentioned them in the PR https://github.com/bounswe/bounswe2022group1/pull/788 as follows: 

> I implemented annotations functionality in backend. 
> One may check http://3.89.218.253:8001/admin/. The endpoints are http://3.89.218.253:8001/app/annotation/ and  http://3.89.218.253:8001/app/delete-annotation/. The former has get, post and patch methods, whereas the latter endpoint has a post method. The examples are below: :

**Comment by kkadirkkalkan** [comment]
Nice work. I am closing this issue.
