### ISSUE TITLE
Frontend - Updating UI of Add and Edit Resource Pages

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#879]
**Issue Description:**
Add and edit resource pages are very similar-looking pages. They both have some problems in terms of UI. For example, the content of the pages is not centered, the headers are so small and the paddings are disproportionate. I will fix those issues.

**Tasks to Do:**

- [x] center the content
- [x] fix sizes of headers
- [x] fix paddings
- [x] remove not meaningful headers

*Task Deadline:* 
27.12.2022 12:00

*Final Situation:*
I fixed the UI of add and edit resource pages.

Relevant commit: https://github.com/bounswe/bounswe2022group1/commit/fd339d6c09317bc72dd342d8af45b6e677f8f3de

Screenshot:
![image](https://user-images.githubusercontent.com/46002371/209604799-d796d492-aba5-4ab5-bc91-1f3c1c29cd84.png)

*Reviewer:*  

*Review Deadline:*
27.12.2022 12:00
