### ISSUE TITLE
Updating README File for Instructions of Installing Dependencies

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#881]
**Issue Description:**

I am going to update instructions of [README](https://github.com/bounswe/bounswe2022group1/tree/frontend#readme) file for installing dependencies.

**Tasks to Do:**

- [x] add issue labels
- [x] add reviewer
- [x] add related links
- [x] update `README.md` file
- [x] create a PR

*Task Deadline: 27/12/2022 7:00 am* 

*Final Situation: `README.md` updated*

*Reviewer: @kadirgokhann*  

*Review Deadline: 27/12/2022 8:00 am*
