### ISSUE TITLE
Creating Splash Screen

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#919]
**Issue Description:**

Creating a splash screen for the application
Splash screen page design

**Tasks to Do:**

- [x] Design of splash screen
- [x] Integration of 3rd party libraries
- [x] Adjusting the waiting time on the splash screen according to the opening speed of the application
- [x] Adding progress bar
- [x] Adding some lottie files to make it look nice as a design

*Task Deadline:* 27.12.2022

**Comment by harunerkurt** [comment]
<img width="374" alt="Screenshot 2022-12-27 at 10 50 31" src="https://user-images.githubusercontent.com/49256548/209635323-00f964f8-7f36-485f-a967-bafc837fcac8.png">
