### ISSUE TITLE
Design and Creation of Landing Page

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#925]
**Issue Description:**

Add a description of the issue

**Tasks to Do:**

- [x] design of landing page
- [x] add some lotie files to landing page
- [x] develope related codes for landing page

*Task Deadline:* 27.12.2022

**Comment by harunerkurt** [comment]
<img width="381" alt="Screenshot 2022-12-27 at 10 50 22" src="https://user-images.githubusercontent.com/49256548/209635279-07d598f8-5ed3-43c3-84ba-cc96f977d229.png">
