### ISSUE TITLE
Testing Latest Version of Frontend App

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#926]
**Issue Description:**

I am testing our app's latest version to handle bugs if there is any and to understand features newly added whether works smoothly or not. I am checking through [this](http://budemii.space) domain.

**Tasks to Do:**

- [ ] add issue labels
- [ ] add related links
- [ ] give feedbacks to teammates

*Task Deadline: 27/12/2022 12:30 pm* 

*Final Situation:*
