### ISSUE TITLE
Add Onboarding Activity

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#932]
**Issue Description:**

To make the application an introductory page so that the application can be understood by users

**Tasks to Do:**

- [x] Design of page
- [x] Develope related codes
- [x] add some lotie files for animation
- [x] Adding a button to go to the homepage

*Task Deadline:* 

27.12.2022

**Comment by harunerkurt** [comment]
<img width="381" alt="Screenshot 2022-12-27 at 10 50 40" src="https://user-images.githubusercontent.com/49256548/209634617-a64f5e10-30ef-47d5-9039-b32d4df9310b.png">
<img width="385" alt="Screenshot 2022-12-27 at 10 50 50" src="https://user-images.githubusercontent.com/49256548/209634628-e233f2fc-2e9f-45da-80d0-5a853fa18039.png">
<img width="382" alt="Screenshot 2022-12-27 at 10 50 58" src="https://user-images.githubusercontent.com/49256548/209634634-66eac1dc-fd90-4525-a195-ef27691db5e5.png">
