### ISSUE TITLE
Set application settings

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#934]
**Issue Description:**

In order to get build as a release apk, some settings need to be made

**Tasks to Do:**

- [x] add app icon
- [x] change application id to com.budemi.app
- [x] fix gradle build error
- [x] fix linking reseorce error
- [x] generating a keystore

*Task Deadline:* 

27.12.2022

**Comment by harunerkurt** [comment]
I designed an app icon
<img width="387" alt="Screenshot 2022-12-27 at 10 50 05" src="https://user-images.githubusercontent.com/49256548/209636376-5d441f97-5952-455c-91cb-66ff6b61a880.png">

**Keystore informations**
alias: android
password: bounswe2022group1

**Comment by harunerkurt** [comment]
Application apk is here

[budemi.apk.zip](https://github.com/bounswe/bounswe2022group1/files/10307010/budemi.apk.zip)
