### ISSUE TITLE
Checking PR and Merging Frontend Branch to Master

### ISSUE THREAD

**Issue by hseyyidkaplan** [bounswe/bounswe2022group1#938]
**Issue Description:**

We are going to check PR from `frontend` to `master` for latest version of our frontend app, resolve conflicts and merge this branch. Thanks all of my teaammates for their efforts, health to our hands 🤝 

**Tasks to Do:**

- [x] add issue labels
- [x] add related links
- [x] check PR
- [ ] resolve conflicts
- [ ] merge `frontend` to `master`

*Task Deadline: 27/12/2022 12:15 pm* 

*Final Situation: failed*

**Comment by hseyyidkaplan** [comment]
I couldn't handle this issue because of the problem that I faced while cloning `master` branch to my local. I tried an hour but couln't solve the problem, We shouldn't leave this task at the eleventh hour.

![image](https://user-images.githubusercontent.com/32467338/209648155-9843aeb4-0e1f-4311-84bb-8d957ea9eac7.png)
