### ISSUE TITLE
Objectives of Android Team for Milestone3

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#941]
**Issue Description:**
Until the milestone3, objectives as Android Team is as follows

**Tasks to Do:**

- [x] Determining Primary and Secondary colors to align with front-end team in terms of design.
- [x] Creating Splash Screen
- [x] Creating Landing Page
- [x] There is no content or such thing. Everything is a resource. Change the names accordingly.
- [x] Resources should be added via markdown.
- [x] Discussion, members and notes should be split into different pages for better UI/UX experience.
- [x] Show attributes of learning spaces (members, upvotes etc.) for better UI/UX experience.
- [x] Give shortcut for favorite learning space.
- [x] Annotation functionality should be implemented.
- [x] All designs should be reviewed for better UI/UX experience.

*Task Deadline:* 
27.12.2022

*Review Deadline:*
27.12.2022
