### ISSUE TITLE
Mustafa Atay - Milestone 3 Reports

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#958]
**Issue Description:**
I will prepare my parts of the milestone 3 report.

**Tasks to Do:**

- [x] prepare an individual report
- [x] prepare a summary of work done by Mustafa Atay
- [x] write annotations part of the group report
- [x] write progress according to requirements of the group report

*Task Deadline:* 
02.01.2023 23:00

*Final Situation:*
I prepared those documentations and updated the following wiki pages accordingly:
- https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-3-Individual-reports
- https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-3-Group-Review
