### ISSUE TITLE
Ece Sarkın - individual report

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#961]
**Issue Description:**

I should write my individual report for Milestone 3.

**Tasks to Do:**

- [x] retrieve info from old reports
- [x] update my weekly effort
- [x] write the individual report

*Task Deadline:*  02.01.2023 22.30

**Comment by ecesrkn** [comment]
I have logged my contributions under this wiki page:
https://github.com/bounswe/bounswe2022group1/wiki/Customer-Milestone-3-Individual-reports
