### ISSUE TITLE
Harun Erkurt - individual report

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#963]
**Issue Description:**

I should write my individual report for Milestone 3.

**Tasks to Do:**

- [x] retrieve info from old reports
- [x] update my weekly effort
- [x] write the individual report

*Task Deadline:*  02.01.2023 22.30
