### ISSUE TITLE
Research on Lottie Files and third party libraries about animation

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#964]
**Issue Description:**

Adding animations to make the application look better and researching it

**Tasks to Do:**

- [x] Research on lottie files
- [x] Research on thirdy party libraries about animation
- [x] Integration of related lottie files

*Task Deadline:* 

20.12.2022

**Comment by harunerkurt** [comment]
I found 5 lottie files and I integrated
'com.airbnb.android:lottie:3.7.0' for lottie animation
